DROP DATABASE IF EXISTS contacts;
CREATE DATABASE IF NOT EXISTS contacts;
GRANT ALL ON contacts.* TO root@'%';
--
USE contacts;
--
CREATE TABLE ADDRESS
	(ID BIGINT AUTO_INCREMENT NOT NULL PRIMARY KEY,
	ADDRESS1 VARCHAR(80) NOT NULL,
	ADDRESS2 VARCHAR(80),
	CITY VARCHAR(80) NOT NULL,
	COUNTRY VARCHAR(30) NOT NULL,
	POSTAL_CODE VARCHAR(10) NOT NULL,
	STATE VARCHAR(10),
	VERSION INTEGER);
--
CREATE TABLE CONTACT(
ID BIGINT AUTO_INCREMENT NOT NULL PRIMARY KEY,
FIRSTNAME VARCHAR(30) NOT NULL,
LASTNAME VARCHAR(60) NOT NULL,
VERSION INTEGER,
BILLING_ADDRESS_ID BIGINT,
SHIPPING_ADDRESS_ID BIGINT,
CONSTRAINT FK_CONTACT_BILLING_ADDRESS FOREIGN KEY(BILLING_ADDRESS_ID) REFERENCES ADDRESS(ID),
CONSTRAINT FK_CONTACT_SHIPPING_ADDRESS FOREIGN KEY(SHIPPING_ADDRESS_ID) REFERENCES ADDRESS(ID));
--
CREATE TABLE EMAIL_ADDRESS(
ID BIGINT AUTO_INCREMENT NOT NULL PRIMARY KEY,
CONTACT_ID BIGINT NOT NULL,
VALUE VARCHAR(120) NOT NULL,
VERSION INTEGER,
CONSTRAINT FK_EMAIL_ADDRESS_CONTACT FOREIGN KEY(CONTACT_ID) REFERENCES CONTACT(ID)
);
--
CREATE TABLE PHONE(
ID BIGINT AUTO_INCREMENT NOT NULL PRIMARY KEY,
CONTACT_ID BIGINT NOT NULL,
NUMBER VARCHAR(20) NOT NULL,
TYPE INTEGER NOT NULL,
VERSION INTEGER,
CONSTRAINT FK_PHONE_CONTACT FOREIGN KEY(CONTACT_ID) REFERENCES CONTACT(ID)
);
